<!DOCTYPE html>
<html>
<head>
	<title>Quiz</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
<h1 style="text-align: center; font-family: Cabin Sketch; font-size: 50px;">Test Your Skills </h1>
<div class="col-xl-2" style="padding: 7em; background-color: #eee; font-family: monospace;">
	<h2 style="font-family: Cabin Sketch; font-size: 40px;">Instruction</h2><br><br>
	
		<h3><li>There are 10 question on a particular topic.</li></h3><br>
		<h3><li>Each question is generated by order only when the last one was correct.</li></h3><br>
		<h3><li>Afterselecting your answer submit that and go for next.</li></h3><br>
		<h3><li>No Time Limit.</li></h3><br>

	
	<a href="quiz1.php" ><button class="btn btn-success" style="font-size: 23px; font-family: Roborto Sans-Serif; margin-left: 32px;">Start Quiz</button></a> 
</div>
</body>
</html>